{
 "title": "Brew House",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temp",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "farenheit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *9/5 + 32 " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "DHT11" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "DHT11" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "pressurehg",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/3386.389" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "BMP180" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Moisture" }
   ],
   "targets": [
    {
     "alias": "DHT11 Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "DHT11" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "farenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "DHT11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "DHT11" }
     ]
    },
    {
     "alias": "BMP180",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "BMP180" }
     ]
    }
   ]
  }
 ]
}